Incorporated previous changes from Matt to upgrade to Boost 1.55.
Unfortunately, this currently has build problems:

SHA1.cpp
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(96) : error C2039: 'set_timer_resolution' : is not a member of 'boost::interprocess::winapi'
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(96) : error C3861: 'set_timer_resolution': identifier not found
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(105) : error C2039: 'set_timer_resolution' : is not a member of 'boost::interprocess::winapi'
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(105) : error C3861: 'set_timer_resolution': identifier not found
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(116) : error C2039: 'set_timer_resolution' : is not a member of 'boost::interprocess::winapi'
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(116) : error C3861: 'set_timer_resolution': identifier not found
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(118) : error C2039: 'query_performance_frequency' : is not a member of 'boost::interprocess::winapi'
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(118) : error C3861: 'query_performance_frequency': identifier not found
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(134) : error C2039: 'get_tick_count' : is not a member of 'boost::interprocess::winapi'
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(134) : error C3861: 'get_tick_count': identifier not found
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(162) : error C2039: 'sleep_tick' : is not a member of 'boost::interprocess::winapi'
libraries\boost_1_55_0\boost/interprocess/detail/os_thread_functions.hpp(162) : error C3861: 'sleep_tick': identifier not found